# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleCalendar2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 

pod 'FSCalendar'
  pod 'CalculateCalendarLogic' 

  # Pods for sampleCalendar2

  target 'sampleCalendar2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleCalendar2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
